### ISSUE TITLE
P29のNOTEの説明について

### ISSUE THREAD

**Issue by y-vectorfield** [LambdaNote/errata-cpu-for-programmer-1-1#313]
P29のNOTEの1行目後半〜2行目にかけての以下の記述ですが、
> 先行命令の「実行完了」と先行命令の「フェッチ開始」とが逐次化されるわけではないことに注意してください。

文脈や後続の説明との整合性から、以下の記載が正しいのではないかと思いました。

先行命令の「実行完了」と**後続**命令の「フェッチ開始」とが逐次化されるわけではないことに注意してください。

**Comment by takenobu-hs** [comment]
確認有難うございます！ :pray:

**Comment by k16shikano** [comment]
ありがとうございます。  #29 に転記しました。こちらは閉じさせていただきます。
