### ISSUE TITLE
P38の3.8節でのサンプルコードの説明について

### ISSUE THREAD

**Issue by y-vectorfield** [LambdaNote/errata-cpu-for-programmer-1-1#314]
P38の3.8節でのサンプルコードの説明で

> 加算命令(add)、乗算命令(mul)、ロード命令(mov)

との記載が有りますが、ロード命令は正しくはloadですが、ソースコードの内容と照らし合わせた結果

> 加算命令(add)、乗算命令(mul)、転送命令(mov)

が正しい説明なのではないでしょうか。

**Comment by takenobu-hs** [comment]
確認と指摘を有難うございます！

ここについては、著者の意図としては現在のままの、

> 加算命令(add)、乗算命令(mul)、ロード命令(mov)

で正しいです。

この箇所では、本章のアセンブリ例との対応からロード命令としてx86の"mov"命令を意図して説明を行っています。
（１章の表1.1のように、x86のロード命令は"mov"となります。)

ただおそらく、この章の表3.1にてロード命令に"load"と記載していることから、読者の方を混乱させているものと思います。
将来的に機会があれば、ここではロード命令としてx86のmovを意図していることをわかりやすくする注釈を入れるか、表3.1側の記載を工夫するなりして、誤解を生みにくくしようと思います。 有難うございました。

**Comment by k16shikano** [comment]
https://github.com/LambdaNote/errata-cpu-for-programmer-1-1/issues/38 にenhancement として転記済み
